In [1]:
import pandas as pd
import numpy as np
import os #Interacts with the operating system, e.g. paths, mkdir
import seaborn as sns
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D # Allows ploting in a 3D graph

from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix,classification_report

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
file_path = r'C:/Users/crist/Documents/02.MSU_MsDataScience/2024.SPRING/04.CSIT598_03SP24_MACHINE-LEARNING/02.MACHINE_LEARNING_SP23/PowerPlantsintheU_Export_TableToExcel.xlsx'
df = pd.read_excel(file_path)

In [4]:
Scolumns = ['sector_nam','State','Total_MW']
df[Scolumns]

             sector_nam           State  Total_MW
0      Electric Utility       Wisconsin       2.3
1      Electric Utility       Wisconsin       1.3
2      Electric Utility       Wisconsin      79.0
3      Electric Utility       Wisconsin       3.8
4      Electric Utility       Wisconsin       2.6
...                 ...             ...       ...
12003       IPP Non-CHP  North Carolina       3.0
12004       IPP Non-CHP  North Carolina       3.0
12005       IPP Non-CHP  North Carolina       5.0
12006       IPP Non-CHP        New York       1.4
12007       IPP Non-CHP    Pennsylvania       1.1

[12008 rows x 3 columns]